/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Fluentis ARM Documentation",
  "tagline": "La guida progettata per supportarti nella parametrizzazione e nell’uso dell’Application Resource Manager",
  "url": "https://docs.fluentis.com",
  "baseUrl": "/Arm/",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "favicon": "img/fluentis-32x32px.png",
  "organizationName": "Fluentis srl",
  "projectName": "ARM",
  "i18n": {
    "defaultLocale": "it-IT",
    "locales": [
      "en-US",
      "it-IT"
    ],
    "localeConfigs": {
      "en-US": {
        "label": "English",
        "direction": "ltr"
      },
      "it-IT": {
        "label": "Italiano",
        "direction": "ltr"
      }
    },
    "path": "i18n"
  },
  "themeConfig": {
    "navbar": {
      "title": ".arm",
      "logo": {
        "alt": "Logo",
        "src": "img/fluentis.svg",
        "className": "logo"
      },
      "items": [
        {
          "to": "docs/release-notes/intro",
          "label": "Release Notes",
          "position": "right"
        },
        {
          "type": "doc",
          "position": "left",
          "docId": "arm/intro",
          "label": "Application Resource Manager"
        },
        {
          "type": "localeDropdown",
          "position": "right",
          "dropdownItemsBefore": [],
          "dropdownItemsAfter": []
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Fluentis Documentation",
          "items": [
            {
              "label": "Fluentis Live Update",
              "href": "https://docs.fluentis.com/FluentisLiveUpdate/"
            },
            {
              "label": "Fluentis ERP",
              "href": "https://docs.fluentis.com/FluentisErp/"
            }
          ]
        },
        {
          "title": "Integration",
          "items": [
            {
              "label": "Integration",
              "href": "https://docs.fluentis.com/Integration/"
            }
          ]
        },
        {
          "title": "Fluentis Training",
          "items": [
            {
              "label": "Training",
              "href": "https://training.fluentis.com/"
            }
          ]
        },
        {
          "title": "About Fluentis",
          "items": [
            {
              "label": " Web Site",
              "href": "https://www.fluentis.com/it/",
              "className": "icon bi bi-arrow-up-right-circle-fill"
            },
            {
              "label": " Instagram",
              "href": "https://www.instagram.com/fluentis.erp/",
              "className": "icon bi bi-instagram"
            },
            {
              "label": " Facebook",
              "href": "https://www.facebook.com/FluentisSrl",
              "className": "icon bi bi-facebook"
            }
          ]
        }
      ],
      "copyright": "Fluentis SRL 2024 | C.F. e P.IVA IT01720550936"
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "prism": {
      "additionalLanguages": [],
      "theme": {
        "plain": {
          "color": "#bfc7d5",
          "backgroundColor": "#292d3e"
        },
        "styles": [
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(105, 112, 152)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "string",
              "inserted"
            ],
            "style": {
              "color": "rgb(195, 232, 141)"
            }
          },
          {
            "types": [
              "number"
            ],
            "style": {
              "color": "rgb(247, 140, 108)"
            }
          },
          {
            "types": [
              "builtin",
              "char",
              "constant",
              "function"
            ],
            "style": {
              "color": "rgb(130, 170, 255)"
            }
          },
          {
            "types": [
              "punctuation",
              "selector"
            ],
            "style": {
              "color": "rgb(199, 146, 234)"
            }
          },
          {
            "types": [
              "variable"
            ],
            "style": {
              "color": "rgb(191, 199, 213)"
            }
          },
          {
            "types": [
              "class-name",
              "attr-name"
            ],
            "style": {
              "color": "rgb(255, 203, 107)"
            }
          },
          {
            "types": [
              "tag",
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 114)"
            }
          },
          {
            "types": [
              "operator"
            ],
            "style": {
              "color": "rgb(137, 221, 255)"
            }
          },
          {
            "types": [
              "boolean"
            ],
            "style": {
              "color": "rgb(255, 88, 116)"
            }
          },
          {
            "types": [
              "keyword"
            ],
            "style": {
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "doctype"
            ],
            "style": {
              "color": "rgb(199, 146, 234)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "color": "rgb(178, 204, 214)"
            }
          },
          {
            "types": [
              "url"
            ],
            "style": {
              "color": "rgb(221, 221, 221)"
            }
          }
        ]
      },
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "presets": [
    [
      "@docusaurus/preset-classic",
      {
        "docs": {
          "sidebarPath": "C:\\Users\\dario.belluz\\Desktop\\Arm\\sidebars.js",
          "showLastUpdateTime": false
        },
        "theme": {
          "customCss": "C:\\Users\\dario.belluz\\Desktop\\Arm\\src\\css\\custom.css"
        }
      }
    ]
  ],
  "plugins": [
    [
      "C:\\Users\\dario.belluz\\Desktop\\Arm\\node_modules\\@cmfcmf\\docusaurus-search-local\\lib\\server\\index.js",
      {
        "indexDocs": true,
        "indexDocSidebarParentCategories": 0,
        "indexBlog": true,
        "indexPages": false,
        "language": [
          "en",
          "it",
          "pt",
          "ro"
        ],
        "maxSearchResults": 64,
        "lunr": {
          "tokenizerSeparator": {},
          "b": 0.75,
          "k1": 1.2,
          "titleBoost": 5,
          "contentBoost": 1,
          "tagsBoost": 3,
          "parentCategoriesBoost": 2
        }
      }
    ]
  ],
  "baseUrlIssueBanner": true,
  "future": {
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  }
};
